### ISSUE TITLE
Fix remark

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/awesome-cryptography#45]
Right now there are two issues with it:
1. `no-html` in markdown files
2. links break all the time

**Comment by wooorm** [comment]
I was about to open an issue but saw this already, here’s what I would’ve posted:

[`remark`](https://github.com/wooorm/remark) and [`remark-lint`](https://github.com/wooorm/remark-lint) changed a bunch since it was implemented here. Most notably, see the [`remark-lint@6.0.0`](https://github.com/wooorm/remark-lint/releases/tag/6.0.0) changelog, and the [releases for `remark`](https://github.com/wooorm/remark/releases) page to find out more.

Or, feel free to ping us on [Gitter](https://gitter.im/wooorm/remark) or me below!

Cheers 👋
Titus
